# Generated by Django 4.2.11 on 2025-02-21 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Nazev filmu')),
                ('length', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(45), django.core.validators.MaxValueValidator(200)], verbose_name='Delka (min)')),
                ('is_for_adults', models.BooleanField(default=False, verbose_name='Pouze pro dospele')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Hodnoseni')),
            ],
        ),
    ]
