# Generated by Django 4.2.11 on 2025-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
